version: "2"
services:
  gaas-rest:
    image: "dockerhub/repo"
    ports:
      - "8080:8080"
    container_name: gaas-rest
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - $PWD/prometheus.yaml:/etc/prometheus/prometheus.yml
    container_name: prometheus