version: '3.3'
services:
  gaas-rest:
    image: "gaas-prom:latest"
    ports:
      - "8080:8080"
    container_name: gaas-prom
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - $PWD/prometheus.yaml:/etc/prometheus/prometheus.yml
    container_name: prometheus