kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: kai-helm-3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader


