name: CI

on: [ pull_request ]

jobs:
  run-maven-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run build
      run: mvn clean install

  run_ui_tests:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./gaas-ui

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.16.0

    - name: Install dependencies
      run: |
        ls
        cd ./gaas-ui/
        npm run install

    - name: Run tests
      run: npm run test
